server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/urgences_db
    username: postgres
    password: 231005
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  artemis:
    mode: embedded
    embedded:
      enabled: true
      persistent: false
      
    user: artemis
    password: artemis

logging:
  level:
    com.hopital.urgences: DEBUG